### ISSUE TITLE
New landing page igxGrid demo

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-samples#168]
### Description  
Create a new demo for the landing page, that displays more of the newly added features to the `igxGrid`.

The demo should cover a financial scenario.

- [ ] Design
- [ ] Implementation

**Comment by SDinev** [comment]
Scenario 1: CRM

Columns
S = sorting
F = filtering
(U) = summaries
P = pinned

1. customer number (number) F (U = count) P
2. avatar (avatar) P
3. name surname (name) S F P
4. position F
5. company S F (U=max)
6. work email 
7. work phone
8. mobile phone
9. fax
10. tags F
11. work address / street
12. work address / city F
13. work address / post code
14. work address / state F
15. work address / country S F
16. created on (date) S
17. referred by (name) F (U = count, max)
18. birthday (date) F (U = custom - upcoming)
19. last activity (date) S (U = earliest)
20. next activity (date) S (U = earliest)
21. deals total (number) S  
22. deals won (number) S (U = sum, avg, max)
23. ratio (won/lost progress bar)
24. deals lost (number) S (U=sum,avg, max)
25. deals pending (number) S (U=sum, avg, max)
26. estimated sales (amount in USD, sum of pending deals) S (U=sum, avg)
27. actual sales (amount in USD, sum of won deals) S (U=sum, avg)

**Comment by SDinev** [comment]
*** Inventory Data Table ***

Scenario: Owner of a clothes store needs a data table to have an overview of his inventory - availability, how items are performing, what is most profitable, etc.

__Columns__:
1. index /1-3999/
2. item # /196122-318711/
3. item image (?) 
4. manufacturer /GAP/
5. season /autumn-winter/
6. year /2017/
7. category /tops/
8. sub-category /knitwear/
9. item name /cardigan/
10. target /male, female, girls, boys/
11. size /xs-xxl/

12. unit buy price ($) /10-2000/
13. units ordered /20-100/
14. total ($) /col12 * col13/

15. unit sell price ($) /20-2200, 10-100% over unit buy price/
16. units sold /10-100% of col13/
17. total ($) /col15 * col16/

18. units remaining /col13 - col16/ (5-20 = color warn, 0-5 = color error)
19. progress bar (remaining out of ordered)

20. profit ($) / 
21. profit (%) /

**Comment by SDinev** [comment]
Hello Folks, 

I spent some time today to come up with several options for the design. I am not looking into black/dark versions at this point.

1. Version 1: Base design:
![base design](https://user-images.githubusercontent.com/13866657/38942311-228886b0-4337-11e8-8dbd-a06d3b30565a.png)
This is very close to what the default grid would look like. 

2. Version 2: Purple and yellow
I've used the purples in the landing page, and added a yellow color to showcase that we're using both primary and secondary palettes.
![purple yellow](https://user-images.githubusercontent.com/13866657/38942431-6a755f0c-4337-11e8-8611-223df4ca2072.png)

3. Version 3: Blue and Yellow
Using the primary blue and complementing with yellow, this version also fits well with the page. 
![blue yellow copy](https://user-images.githubusercontent.com/13866657/38942582-dc1d7f9a-4337-11e8-8ecb-86a96ccffa4c.png)

4. Version 4: White and Blue
A cleaner, more minimal approach that uses much less color - most of the elements are white, with only shades of blue to make content stand out.
![white blue](https://user-images.githubusercontent.com/13866657/38942598-e5c15e72-4337-11e8-87f5-cdc5b560e41c.png)

Personally, I'd go for 3 or 4. They are clean, more minimal, fit the page well.

Hey, btw, do you have any ideas about the title of the grid? CRM seems kinda unimaginative, the squid might be too far out ;)

Thanks!

**Comment by dkamburov** [comment]
Hello,

You can review the current progress on the sample here - https://stackblitz.com/edit/crm-landing-page-4rd4yl

Thanks!

**Comment by StefanIvanov** [comment]
There is some jumping of the headers and the fill of the progress bar when I use the horizontal scroll. Where does that side effect come from, any idea?

https://infragisticsinc297-my.sharepoint.com/:v:/g/personal/sivanov_infragistics_com/EdvpoohjDvxNv1UHTeu3yFABOY3nh9C3WP5ZLxMHZPvcxg?e=1a9tkM 

https://infragisticsinc297-my.sharepoint.com/:v:/g/personal/sivanov_infragistics_com/EUjd5mVvdN9ApJjhntFekJYBrmvOrhnx35TO69IiWrgXMw?e=EVCera

**Comment by dkamburov** [comment]
I don't see the images, but I believe it is from the styling of filtering toggle. When the headers are having one, they are bigger than when there is no filtering toggle in the current view.

**Comment by dkamburov** [comment]
Some fixes into the sample and summaries enabled
https://stackblitz.com/edit/angular-h8wtqc

**Comment by StefanIvanov** [comment]
Both glitches are fixed and summaries look stunning

**Comment by dkamburov** [comment]
Newer version with the buttons - https://stackblitz.com/edit/angular-qba2bh

**Comment by SDinev** [comment]
badass.

1. There are "count" summaries on **name** and **customer number**, which show the same number. Can we remove the summary under "name"?
2. Columns that are not **sortable** still show a pointer cursor when hovered. There's no action there, however, so it makes it weird and unexpected.
3. Columns show a "**resize**" cursor, but I can't resize when I click and drag. We want to be able to resize columns. 
4. The sample's **height** was designed to have a total of about **650px** for a reason -- to fit in the visible space of a laptop, within a browser + considering our huge unmistakable website monster header
5. The **width** of the content on our website is ~**1172px**, as far as I can see. This should be the size of the grid visible on the webpage.
6. Set the size of the pinned columns to the minimum possible space where it doesn't cut texts, to make sure the grid displays as many non-pinned columns as possible.

**Comment by dkamburov** [comment]
The link is updated https://stackblitz.com/edit/angular-1f54hd

**Comment by dkamburov** [comment]
Sample with fixed width - https://stackblitz.com/edit/angular-bkwlrd

**Comment by StefanIvanov** [comment]
UX is signing off the sample

**Comment by sbozalieva** [comment]
And UX is back!:)

guys let's update the Hidden Columns Dropdown a bit. Here is the result:

<img width="391" alt="screen shot 2018-04-25 at 12 00 03" src="https://user-images.githubusercontent.com/23053821/39236031-453a076c-4880-11e8-9dea-de0589f71326.png">

Discussed with and approved by @SDinev 
Thanks,
Tanya

**Comment by sbozalieva** [comment]
This is a quick mock -up so:
- "Hidden columns" should be left alighned with the checkboxes. 
-  And the styling is the same as the header in the Pinned Dropdown.

Cheers:)

**Comment by kdinev** [comment]
@sbozalieva Good suggestion. We will push an update with this next week.

Also all date columns should have the data as date objects and should apply formatting.
