### ISSUE TITLE
Grid Live-data Update sample, stop button does not work.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular-samples#3477]
### Description  
Grid Live-data Update sample, stop button does not stop live updates.

### Steps to reproduce  

1. Open sample at: https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/live-data#angular-live-data-update-example
2. Click the Live All Prices button.
3. Click the Stop button.

The same works on live: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live-data#angular-live-data-update-example

### Result  
Grid should stop updating, but it doesn't.

### Expected result  
Grid should stop updating when the stop button is clicked.

**Comment by dkamburov** [comment]
@MayaKirova Not sure we need to do anything about it. Might be only on staging, as it seems it works on prod, as we've deployed 18 to prod samples already.

**Comment by MayaKirova** [comment]
@dkamburov Not sure if prod is fully updated or is still showing a cached version, since for me it seems to still use an older version (not 18):
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/10397980/df67ef57-4189-45ec-8d72-569a33293dad)

**Comment by tishko0** [comment]
The issue is caused by the double emit of the selected event, causing the id returned by setInterval to be lost as it gets replaced by the second Id from the second call and it never gets cancelled. 
Issue should be resolved when the following one gets fixed:
https://github.com/IgniteUI/igniteui-angular/issues/14445

**Comment by skrustev** [comment]
Issue still seem to be reproduced even with latest version of igniteui-angular
